version: '3'
services:
  service:
    build: app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./data/static:/opt/app/static
    depends_on:
      - theatre-db

  nginx:
    image: nginx:latest
    volumes:
      - ./data:/data/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - service
    ports:
      - 80:80

  theatre-db:
    image: postgres:16
    env_file:
      - .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./path/openapi.yaml:/swagger.yaml
    env_file:
        - .env
    ports:
        - 8080:8080

volumes:
  pg_data:
  static:

